version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Fran290988fss.
      #postgres
      POSTGRES_DB: proyectom3
      #ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: Fran290988fss.
      DB_NAME: proyectom3
      JWT_SECRET: algunPass123
      # agrega aquí otras variables de entorno necesarias para tu app
    ports:
      - "3000:3000"
    command: npm start

volumes:
  pgdata: